### ISSUE TITLE
Minecraft server console locks up

### ISSUE THREAD

**Issue by theoratkin** [Edenhofer/abs#12]
I'm running a PaperMC server with the [`papermc`](https://github.com/Edenhofer/abs/tree/master/papermc) package with the included [`papermc.sh`](https://github.com/Edenhofer/abs/blob/master/papermc/papermc.sh) script (which, as I understand, is just a copy of the [`minecraftd.sh`](https://github.com/Edenhofer/abs/blob/master/minecraft-server/minecraftd.sh) script from the [`minecraft-server`](https://github.com/Edenhofer/abs/tree/master/minecraft-server) package).

And the problem is, when I exit the console not cleanly, i.e. not with `^B`+`d`, like when SSH connection drops unexpectedly, I'm unable to enter the console again. The command just hangs and there's no way to exit it, `^C` doesn't work.

Looking at the code:

https://github.com/Edenhofer/abs/blob/eaa5b2d0402eef48eb889f443fcfb9f9857660b9/papermc/papermc.sh#L418-L426

It seems like at the line 420 it locks the session with the `wait-for` command, and then unlocks it after the console was detached properly. But when not, the unlock command at the line 422 is never executed. So when trying to open the console again, it just keeps waiting forever on the line 420.

**Comment by Edenhofer** [comment]
Thank you very much for this detailed bug report!

The reason for this lock being there is that we can not allow multiple potential observers of the server (here the idle daemon and you, the user) to both observe the server session. Thus, whenever either of them is connected, it locks the session. The respective line should really only be triggered if you try to connect at the exact same time the idle server triggers its is-player-online check. Since this usually only takes a couple of 100 ms, the user should not feel a delay if in these rare occasions of a race condition.

I see multiple possible solutions:
* We could wait for a specified amount of time and quit afterwards telling the user to manually break the lock. Here, it would make sense to e.g. implement a minimalistic helper function like `$MINECRAFT_SERVER break-lock`.
* Automatically break the lock at some point, .e.g. after waiting x seconds, and restart the idle daemon.
* We trap common exit signals and always remove the lock.
```bash
function clean_up() {
	socket_has_session "${SESSION_NAME}" && ${SUDO_CMD} tmux -L "${SESSION_NAME}" wait-for -U "command_lock" 
	echo
}
# Trap a normal exit as well as termination signals
trap clean_up EXIT SIGHUP SIGINT SIGTERM
```

I am leaning towards the last option. It is in my opinion the cleanest and should catch all common cases. It is in my optionion the optimal solution as long as the process is properly killed with either EXIT, SIGHUP, SIGINT or SIGTERM. Hopefully, this should happen if a SSH connection stalls. Having said that, the first two are probably the most conservative ones.

P.S. the `papermc.sh` script has different defaults than the `minecraftd.sh` scrip. These default are set at the top of the file. Otherwise, yes, they are identical.

**Comment by theoratkin** [comment]
> We trap common exit signals and always remove the lock.

I don't think it will work with SSH, because it doesn't seem to send any signals on connection loss. I tried to use your snippet and close a SSH connection by force with `Enter`+`~`+`.` and the process `papermc console` just keeps running.

Another problem is that removing the lock requires root priviliges, and when SSH connection drops, there's no one to enter the `sudo` password.

So I think instead of trying to do something on exit, it's better to remove the lock after some time when the script is invoked, your second option seems to fit the description, if I understood correctly.

**Comment by Edenhofer** [comment]
I am not sure whether I am really worried about that. You can easily kill this process after a reconnect and via the `trap` in the script, the server will recover correctly.

The problem I see with the second option is that we potentially terminate valid sessions that simply happen to run for a long time. This could easily happen on a machine that is managed by more than one person. We can inherently not distinguish a session that simply hangs versus a session that is open for a long time.

Just to clarify, you must not have root access to run commands as a different user. You simply must allow your user to run commands as a distinct different non-root user. Most importantly, you can safely allow users that shall not have root access to execute command as a different non-root user.

**Comment by Edenhofer** [comment]
I think I found a solution that should resolve your issue: The problem with having many observers is not really that tmux disallows for many sessions being connected, it just doesn't like multiple `pipe-panes`. However, we can distinguish between attached sessions and `pipe-panes` calls and thus allow for multiple observers but only one `pipe-pane` user.

Having said that, one still needs to close all idle sessions! As long as the server thinks that an administrator is connected to the server session, it will pause the player checking.

**Comment by theoratkin** [comment]
> Just to clarify, you must not have root access to run commands as a different user. You simply must allow your user to run commands as a distinct different non-root user. Most importantly, you can safely allow users that shall not have root access to execute command as a different non-root user.

You are right, sorry, I got confused by the root part, you need to be able to run as the `papermc` user rather than root. But it still requires entering your `sudo` password unless you have a rule in the `sudoers` file. But that's not a problem, I should have this rule anyway, I'll add it now.

> I think I found a solution that should resolve your issue: The problem with having many observers is not really that tmux disallows for many sessions being connected, it just doesn't like multiple `pipe-panes`. However, we can distinguish between attached sessions and `pipe-panes` calls and thus allow for multiple observers but only one `pipe-pane` user.

This sounds good!

> Having said that, one still needs to close all idle sessions! As long as the server thinks that an administrator is connected to the server session, it will pause the player checking.

I tend to always have the console open, so that I can check what's going on the server by simply switching the workspace. Does this mean that I shouldn't do that?

**Comment by Edenhofer** [comment]
If you are using the idle_server_daemon, then you should not leave the session open indefinitely. This is because the server is not checking whether a user is online, if someone is connected to the server console.

If you are not using the idle_server_daemon, then always being connected to the server session has no impact.

**Comment by theoratkin** [comment]
Got it, I'm not using it, so it doesn't affect me.

**Comment by Edenhofer** [comment]
Can you do me a favor and test the changes introduced in commit 9553977 ? They should resolve your issue.

Note, I did not release them to the AUR yet so you have to clone this repo manually.

**Comment by theoratkin** [comment]
Yes, the problem is now gone! Thank you so much!

**Comment by Edenhofer** [comment]
Glad to hear that! I am happy to help :)
