### ISSUE TITLE
letsencrypt-git error during installation

### ISSUE THREAD

**Issue by rafaelcapucho** [Edenhofer/abs#2]
Hello,

I'm trying to install letsencrypt using yaourt on updated arch linux and i'm getting errors.

![error-0](https://cloud.githubusercontent.com/assets/163367/14563011/3a83e350-030f-11e6-94a7-40883c2cb904.png)

![error](https://cloud.githubusercontent.com/assets/163367/14563014/40a4e112-030f-11e6-824f-0fc4b76f1b11.png)

Any help? thank you

**Comment by Edenhofer** [comment]
Thanks for the hint! The problem should be fixed.

**Comment by rafaelcapucho** [comment]
@Edenhofer thank you for you effort, now the installation is complete but no executable are generated in the end of the process, in other words, the command letsencrypt ins't available to be used.

The results:
https://paste.ee/r/iJDqn

```
[kepler@localhost ~]$ which letsencrypt
which: no letsencrypt in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
```

Thank you

**Comment by Edenhofer** [comment]
Thanks again, good catch! The problem occured due to letsencrypt being in the transition of moving to a new name probably certbot. Therefore the directory structure has changed slightly. I adapted the according paths in the build function, but forgot to do so when linking the executables. The problem was addressed in 971d425 and certbot (previously letsencrypt) should work just fine.

Btw. I am planning a major redesign and will release an updated package, probably with the name certbot, to the AUR very soon.

**Comment by rafaelcapucho** [comment]
Hello @Edenhofer,

Problem solved!

```
[kepler@localhost ~]$ which certbot
/usr/bin/certbot
[kepler@localhost ~]$ ls -lh /usr/bin/certbot 
lrwxrwxrwx 1 root root 33 Apr 18 17:08 /usr/bin/certbot -> /opt/letsencrypt/venv/bin/certbot
```

Thank you very much

**Comment by Edenhofer** [comment]
No probelm.
The new package [certbot-git](https://aur.archlinux.org/packages/certbot-git/) is now available in the AUR and I would highly recommend switching to it. Not just because of the proper name but mainly becuase it is much more lightweight. Plus it is split into several small packages to give the user the freedom to choose which parts of the program should be installed on the system.
