### ISSUE TITLE
step-by-step instructions for minecraft/spigot server on non-arch systems

### ISSUE THREAD

**Issue by fallerOfFalls** [Edenhofer/abs#5]
I do not know what to do. I don't know how to use any of these files. Instructions would be helpful :)

**Comment by Edenhofer** [comment]
I am afraid I do not understand your question. The repository already has a README which outlines the overall structure of the repository. It is further stated that packages reside in directories and are managed using git-subtrees. In my opinion the most essential details are hence already there. Could you please elaborate as to what you want to do? Maybe I can help you then.

**Comment by fallerOfFalls** [comment]
Ah I seem to have misread github. The link I followed sent me [here](https://github.com/Edenhofer/abs/tree/master/minecraft-server) which of course isn't the repository and therefore didn't show me a readme.

I found it via [this minecraft wiki page](https://minecraft.gamepedia.com/Tutorials/Server_startup_script#Alternative_Startup_Scripts). I was trying to set up my spigot 1.12.2 server on my home Debian install (and not in a system folder such as `/opt` - needs to be in a folder in `/home`), so that it would start and stop with the computer booting and shutting down, which is exactly what your script is advertised as doing.

The readme I now see is for building packages for Arch, which doesn't help me much.

Yes, any help would be greatly appreciated.

**Comment by Edenhofer** [comment]
Ah, I get what you are trying to achieve. Yes, the script should work for your scenario as well. There even is already a script for spigot. It is basically a clone of the minecraft-server management script with altered default values. You can find it [here](https://github.com/Edenhofer/abs/tree/master/spigot).

Note, the automatic starting and stopping is done using systemd (see [`man systemctl`](https://www.freedesktop.org/software/systemd/man/systemctl.html)). Hence, you have to start and enable the service file in order to tell spigot to start upon booting and stop upon shut-down. To place the server files outside `/srv/` just create a configuration file at `/etc/conf.d/spigot.conf` and adapt the values listed [here](https://github.com/Edenhofer/abs/blob/master/spigot/spigot.conf) to your liking.

P.S. the script itself is in now way specific to Arch Linux. It just so happens that I created it for the minecraft AUR package.
